title = "Desguace Solano SL"
baseURL = "https://desguacesolano.es"
languageCode = "es-ES"
theme = "ananke"
resourceDir = "./resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 2 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = 'G-SZBPGZ10N5'
enableRobotsTXT = true

[languages]
  [languages.es]
    title = "Desguace Solano SL"
    weight = 1
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = ""